### ISSUE TITLE
Multi-edge graph does not work (single edge returned)

### ISSUE THREAD

**Issue by pawelmarkowski** [pygraphviz/pygraphviz#162]
Example code (tested on fedora and ubuntu)  pygraphviz installed via pip

`
G=pgv.AGraph(strict=False)
G.add_edge('a','b','first')
G.add_edge('a','b','second')
print(sorted(G.edges(keys=True)))
`
returns
[('a', 'b', 'first')]

**Comment by dschult** [comment]
I have verified that this works on other systems -- indeed it is verbatim in the doctest for ```AGraph.add_edge```. So it has been tested regularly. This is a very strange result. 

Your versions of GraphViz and libcgraph, etc look fine.  Not sure what else to say -- maybe check that you are doing what you think you are doing (i.e. that ```strict``` worked, etc).

**Comment by pawelmarkowski** [comment]
Thanks for the answer ... I do not know what I can say too ... I checked it into two independent machines (private laptop and server) .... Two equal results with missing edge :( On the laptop I use python 3.6, maybe that is the problem?

**Comment by dschult** [comment]
I was able to reconstruct your output!  (using GraphViz 2.40.1 and python 2.7 instead of GraphViz 2.38.0 with python3.6)

Python 3.6 should not be a problem.  Python 3.7 runs into a StopIteration error, but otherwise the versions that you can get pygraphviz to install seem to work fine (including python 2.7).

The GraphViz version is likely what you need to watch for.  I had GraphViz 2.40.1 instead of 2.38.0.   Your version info suggests you have GraphViz 2.38.0 but is it possible you have multiple versions and pygraphviz is getting the libcgraph from a different version of GraphViz?  I'm not sure how to check that.

**Comment by pawelmarkowski** [comment]
@dschult you are right! On laptop with Fedora I have:
graphviz.x86_64                            2.40.1-22.fc28              @updates 
graphviz-devel.x86_64                      2.40.1-22.fc28              @updates 
graphviz-devil.x86_64                      2.40.1-22.fc28              @updates 
graphviz-gd.x86_64                         2.40.1-22.fc28              @updates

Should I downgrade graphviz?

**Comment by dschult** [comment]
Yes -- there's a bug that is fixed in 2.42 whenever that gets released.  We'll shift to that when its ready. But meanwhile only 2.38 works.

**Comment by thekswenson** [comment]
Could you please describe the actions I need to do to downgrade?
I've downgraded my graphviz package but still encounter this problem.

dpkg: warning: downgrading graphviz from 2.40.1-5 to 2.38.0-12ubuntu2.1

In [1]: from pygraphviz import *

In [3]: G=AGraph(strict=False)

In [4]: G.add_edge('a','b','first')

In [5]: G.add_edge('a','b','second')

In [6]: sorted(G.edges(keys=True))
Out[6]: [(u'a', u'b', u'first')]

**Comment by bogdanvuk** [comment]
I made it work by downgrading to 2.38. I've built graphviz from source I downloaded from [http://www.linuxfromscratch.org/blfs/view/7.9/general/graphviz.html](url). 

When installing pygraphviz using pip, I needed to link against the libraries built in this process, and not the ones provided by my distribution (Ubuntu 18.04).

**Comment by dschult** [comment]
Should be fixed when version 2.42 comes out. But that doesn't seem to be a quick process. 
Thanks for confirming that switching to v2.38 works.

**Comment by thekswenson** [comment]
@dschult : I just put this into ipython3 (python version 3.6.7)

```
In [1]: from pygraphviz import *

In [2]: G=AGraph(strict=False)

In [3]: G.add_edge('a','b','first')

In [4]: G.add_edge('a','b','second')

In [5]: sorted(G.edges(keys=True))
Out[5]: [('a', 'b', 'first')]
```
As you can see, it does not seem to be working with python 3.6.7 either. I'm really hard-up for a solution here, as my program is constantly crashing due to this bug.

**Comment by bogdanvuk** [comment]
@thekswenson: The procedure installs graphviz in `~/graphviz-2.38.0` folder. Before using pygraphviz, you will need to set paths as described at the bottom of the procedure. Alternatively, you might also install these libraries system wide, but I haven't tried that.

```
sudo pip3 uninstall pygraphviz
sudo apt purge libgraphviz-dev
cd ~
wget http://pkgs.fedoraproject.org/repo/pkgs/graphviz/graphviz-2.38.0.tar.gz/5b6a829b2ac94efcd5fa3c223ed6d3ae/graphviz-2.38.0.tar.gz
tar xzf graphviz-2.38.0.tar.gz
cd graphviz-2.38.0
./configure --prefix ~/graphviz-2.38.0
make
make install
export CPATH=~/graphviz-2.38.0/include:$CPATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/graphviz-2.38.0/lib/pkgconfig
sudo -E pip3 install --no-cache-dir pygraphviz
```

Before using pygraphviz, export the following:
```
export PATH=~/graphviz-2.38.0/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/graphviz-2.38.0/lib
```

Hope it helps!

**Comment by thekswenson** [comment]
@bogdanvuk : YES.  Thanks very much for the help!

**Comment by bnlawrence** [comment]
I'm on MacOS using an anaconda version of python (and pygraphviz) ... and have this problem. 
Folks might be interested to know that this bug only manifests if you actually use the key to discriminate between the duplicate edges. If you don't need to refer to it, and don't use the key, the bug doesn't manifest (at least for me).

**Comment by corentinbettiol** [comment]
I have the problem on a clean venv using the latest version of `pygraphviz` & `graphviz 2.43.0` as well.

**Comment by dschult** [comment]
Is there a reason you are using Graphviz 2.43.0?
The current version is 9.0.0.   

I don't know that it makes any difference, but it seems like an obvious place to start.

**Comment by corentinbettiol** [comment]
> Is there a reason you are using Graphviz 2.43.0?

Yeah, I'm on ubuntu 20.04 LTS, still on Expanded Security Maintenance (ESM).

The version of graphviz available on Focal Fossa apt repo is still on [2.43.2](https://packages.ubuntu.com/focal/graphviz).

I may need to build a newer version of graphviz myself since it seems that there's no APT archive for an up-to-date graphviz version for older (but still maintained) ubuntu releases.

**Comment by MridulS** [comment]
@corentinbettiol you can try using graphviz with conda-forge too?

**Comment by dschult** [comment]
Ahhh... whoops... I got distracted by the version number and lost track of the issue itself.
My apologies.

To allow multiedges in pygraphviz the AGraph must have its `strict` parameter set to `False`.
```python
import pygraphviz
A = pygraphviz.AGraph(directed=True, strict=False)
A.add_edge(1, 2, "a")
A.add_edge(1, 2, "b")

A.edges(keys=True)    #   ->    [('1', '2', 'a'), ('1', '2', 'b')]

**Comment by rossbar** [comment]
AFAICT this is no longer an issue for pygraphviz 2.0 - see gh-621. You can try for yourself with the prerelease, e.g. `pip install --pre pygraphviz`.

I will go ahead and close as resolved - if the issue persists, please open a new issue with environment info + a reproducer.
